name: focalboard-docker

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
 
permissions:
   contents: write
   pull-requests: write

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.12.2
        
    - name: Install Terraform Docs
      run: |
         wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz         
         tar -xvzf terraform-docs-v0.16.0-linux-amd64.tar.gz        
         mv terraform-docs /usr/local/bin/

    - name: Verify Terraform Docs Installation
      run: terraform-docs --version

    - name: Terraform Init
      run: terraform init
      
    - name: Validate Terraform
      run: terraform validate
      
    - name: Format Terraform code 
      run: terraform fmt -recursive

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Generate Terraform Docs
      run: |
        chmod +x terraform-docs.sh
        ./terraform-docs.sh

    - name: Comment Terraform Docs
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: terraform-docs.md

    - name: Apply Terraform
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
