name: focalboard-docker

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - terminate

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125784755:role/uc1-alb-oidc
          aws-region: us-east-1
           
      - name: Terraform test
        id: test
        run: terraform test
        continue-on-error: true 
      
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true

      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz | tar xz
          sudo mv conftest /usr/local/bin

      - name: Terraform Init & Plan
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
          
      # - name: Format Terraform code 
      #   run: terraform fmt -recursive

      - name: Run OPA Policy Check
        run: conftest test tfplan.json --policy policy/
        continue-on-error: true
     
      # - name: Terraform Apply (from saved plan)
      #   if: github.event.inputs.action == 'apply'
      #   run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'terminate'
        run: terraform destroy -auto-approve
